parameters:
  - name: dependsOnEnv
    type: string
    default: ''
  - name: condition
    type: string
    default: 'always()'
  - name: runStage
    type: string
    default: false

stages:
  - stage: Build
    # ${{ if eq(parameters.dependsOnEnv, '') }}:
    #   dependsOn: []
    # ${{ if ne(parameters.dependsOnEnv, '') }}:
    #   dependsOn: '${{parameters.dependsOnEnv}}'
    condition: ${{ parameters.condition }}
    pool:
      vmImage: 'ubuntu-latest'
    variables:
      - template: ../variables/variables-common.yaml
    jobs:
      - job: BasicValidation
        steps:
          - template: ../steps/tf-install.yaml
          - template: ../steps/tf-init.yaml
            parameters:
              useBackend: false
          - template: templates/tests/terraform/allTests.yaml@azTemplates
            parameters:
              terraformPath: $(System.DefaultWorkingDirectory)