parameters:
  - name: dependsOnEnv
    type: string
    default: ''
  - name: condition
    type: string
    default: 'always()'

steps:
  - template: ../steps/tf-install.yaml
  - template: ../steps/tf-init.yaml
    parameters:
      useBackend: false
  - template: templates/tests/terraform/allTests.yaml@azTemplates
    parameters:
      terraformPath: $(System.DefaultWorkingDirectory)