trigger: none

pr: none

schedules:
- cron: "0 7 * * 1" 
  displayName: Weekly Pipeline Schedule
  branches:
    include:
    - master
  always: true

parameters:
- name: envs
  displayName: Wowza Environment
  type: object
  values: []
  default: ['stg', 'prod']

resources:
  repositories:
    - repository: azTemplates
      type: github
      name: hmcts/azure-devops-templates
      ref: master
      endpoint: hmcts

variables:
- ${{ each env in parameters.envs }}:
  - template: ./pipeline/variables/variables-${{ lower(env) }}.yaml

jobs:
- ${{ each env in parameters.envs }}:
  - job: CertGen${{ env }}
    displayName: 'Generate Certificate for ${{ env }}'
    steps:
      - template: templates/Azure/Certificates/Request.yaml@azTemplates
        parameters:
          subscriptionName: ${{ variables.subscriptionName }}
          product: "cvp"
          environment: ${{ lower(env) }}
          domain: "${{ variables.dns }}"
          keyVaultName: "cvp-${{ lower(env) }}-kv"
