trigger:
  - master
pr:
  - master

resources:
  repositories:
    - repository: azTemplates
      type: github
      name: hmcts/azure-devops-templates
      ref: master
      endpoint: hmcts

parameters:
  - name: envs
    displayName: Environments
    type: object
    values: []
    default: ['sbox','stg','prod']

variables:
  - template: ./pipeline/variables/variables-common.yaml

stages:

  - template: pipeline/stages/build.yaml 

  - ${{each env in parameters.envs}}:
  
    - stage: check_resource_group_exists_${{ env }}
      displayName: Check if resource group exists - ${{ env }}
      pool:
        vmImage: 'ubuntu-latest'
      jobs:
        - job:
          steps:
            - task: AzureCLI@2.236.0
              displayName: Check if resource group exists
              inputs:
                azureSubscription: 'DTS-SHAREDSERVICES-${{env}}'
                scriptType: 'bash'
                scriptLocation: 'scriptPath'
                scriptPath: $(System.DefaultWorkingDirectory)/scripts/check-for-rg.sh
                arguments: "$(env)"

    - template: pipeline/stages/plan.yaml
      parameters:
        env: ${{env}}
        resource_group_exists: $(resource_group_exists)
        ${{ if and(ne(env, 'prod') , contains(lower(variables['Build.SourceBranch']), lower(variables.release_branch_prefix))) }}:
          runStage: 'false'
        ${{ if and(eq(env, 'stg'), eq(contains(lower(variables['Build.SourceBranch']), lower(variables.release_branch_prefix)), False )) }}: # stg env + not release
          runStage: 'true'
          dependsOnEnv: 'sbox'
        ${{ if and(eq(env, 'prod'), eq(contains(lower(variables['Build.SourceBranch']), lower(variables.release_branch_prefix)), False )) }}: # prod env + not release
          runStage: 'true'
          dependsOnEnv: 'stg'

          
    - template: pipeline/stages/deploy.yaml
      parameters:
        env: ${{env}}
        resource_group_exists: $(resource_group_exists)
        ${{ if and(eq(env, 'prod'), contains(lower(variables['Build.SourceBranch']), lower(variables.release_branch_prefix))) }}:  # prod + not release
          runStage: 'true' 
        ${{ if and(ne(env, 'prod'), eq(contains(lower(variables['Build.SourceBranch']), lower(variables.release_branch_prefix)), False )) }}: # not prod + not release
          runStage: 'true'

    - template: pipeline/stages/test.yaml
      parameters:
        env: ${{env}}
        ${{ if and(eq(env, 'prod'), contains(lower(variables['Build.SourceBranch']), lower(variables.release_branch_prefix))) }}:  # prod + release
          runStage: 'true' 
        ${{ if and(ne(env, 'prod'), eq(contains(lower(variables['Build.SourceBranch']), lower(variables.release_branch_prefix)), False )) }}: # not prod + not release
          runStage: 'true'