trigger: none

pr: none

parameters:
- name: environment
  displayName: WWowza Environment
  type: string
  values:
  - 'STG'
  - 'SBOX'
  
- name: vms
  displayName: 'Number of Wowza VMs that should be running?'
  type: number
  values:
  - 0
  - 1
  - 2