trigger:
  - none

pr:
  - none

schedules:
- cron: "0 7 * * 1" 
  displayName: Weekly Pipeline Schedule
  branches:
    include:
    - master
  always: true

parameters:
- name: envs
  displayName: Wowza Environment
  type: object
  values: ['stg', 'prod', 'sbox']
  default: ['stg', 'prod']

resources:
  repositories:
    - repository: azTemplates
      type: github
      name: SamKompfner-HMCTS/azure-devops-templates
      ref: VIH-10935-fix_missing_intermediate_cert
      endpoint: SamKompfner-HMCTS

jobs:
- ${{ each env in parameters.envs }}:
  - job: CertGen${{ env }}
    displayName: 'Generate Certificate for ${{ env }}'
    variables:
      - template: .\pipeline\variables\variables-${{ lower(env) }}.yaml
    steps:
      - template: templates\Azure\Certificates\Request.yaml@azTemplates
        parameters:
          subscriptionName: ${{variables.subscriptionName}}
          product: "cvp"
          environment: ${{lower(env)}}
          domain: "${{ variables.dns }}"
          keyVaultName: "cvp-${{lower(env)}}-kv"
