trigger:
  - none

pr:
  - none

schedules:
- cron: "0 * * * *"  
  displayName: Weekly Pipeline Schedule
  branches:
    include:
    - VIH-0000-CronJob-Test
  always: true

parameters:
- name: env
  displayName: Wowza Environment
  default: 'SBOX'
  type: string
  values:
  - 'STG'
  - 'SBOX'
  - 'PROD'

variables:
  - template: ./pipeline/variables/variables-${{lower(parameters.env)}}.yaml

resources:
  repositories:
    - repository: azTemplates
      type: github
      name: hmcts/azure-devops-templates
      ref: master
      endpoint: hmcts

jobs:
  - job: CertGen${{parameters.env}}
    displayName: 'Generate Certificate for ${{parameters.env}}'
    steps:
      - template: templates\Azure\Certificates\Request.yaml@azTemplates
        parameters:
          subscriptionName: ${{variables.subscriptionName}}
          product: "cvp"
          environment: ${{lower(parameters.env)}}
          domain: "${{ variables.dns }}"
          keyVaultName: "cvp-${{lower(parameters.env)}}-kv"

# Notification settings
trigger: none  
pr: none  

# Notification block for email notifications
pr:
  branches:
    include:
    - VIH-0000-CronJob-Test
  - job: SendEmailOnFailure
    displayName: Send email notification on failure
    condition: failed()  # Notify when the pipeline fails
    steps:
    - task: SendEmail@1
      inputs:
        subject: 'Pipeline Failed: ${{ parameters.env }}'
        body: 'The pipeline for environment ${{ parameters.env }} has failed.'
        to: 'himesh.patel@hmcts.net'  
