trigger:
  - master
pr:
  - master
variables:
  location: 'UK South'
  locationCanonical: uksouth
  env: sbox
  stack: application
  service: 01-cvp-audio-ingress
steps:
  - task: TerraformInstaller@0
    displayName: Install Terraform
    inputs:
      terraformVersion: '0.12.24'
  - task: TerraformCLI@0
    inputs:
      command: 'init'
      commandOptions: '-backend=false'
  - task: TerraformCLI@0
    displayName: Validate Terraform
    inputs:
      command: 'validate'
      commandOptions: '-no-color'
  - script: terraform fmt -check=true
    displayName: Check Formatting

  - task: TerraformCLI@0
    inputs:
      command: 'init'
      backendType: 'azurerm'
      backendServiceArm: '$(subscriptionName)'
      ensureBackend: true
      backendAzureRmResourceGroupName: 'cvp-sbox-rg'
      backendAzureRmResourceGroupLocation: '$(locationCanonical)'
      backendAzureRmStorageAccountName: 'cvpsboxterraform'
      backendAzureRmContainerName: 'terraform-state'
      backendAzureRmKey: '$(location)/$(env)/$(stack)/$(service)/terraform.tfstate'
  - task: TerraformCLI@0
    displayName: Plan
    inputs:
      command: 'plan'
      environmentServiceName: $(subscriptionName)