trigger:
  - none

pr:
  - none

schedules:
- cron: "*/30 * * * *"  
  displayName: Weekly Pipeline Schedule
  branches:
    include:
    - VIH-0000-CronJob-Test
  always: true

parameters:
- name: env
  displayName: Wowza Environment
  default: 'SBOX'
  type: string
  values:
  - 'STG'
  - 'SBOX'
  - 'PROD'

variables:
  - template: ./pipeline/variables/variables-${{lower(parameters.env)}}.yaml

resources:
  repositories:
    - repository: azTemplates
      type: github
      name: hmcts/azure-devops-templates
      ref: master
      endpoint: hmcts

jobs:
  - job: CertGen${{parameters.env}}
    displayName: 'Generate Certificate for ${{parameters.env}}'
    steps:
      - template: templates\Azure\Certificates\Request.yaml@azTemplates
        parameters:
          subscriptionName: ${{variables.subscriptionNamegg}}
          product: "cvp"
          environment: ${{lower(parameters.envgg)}}
          domain: "${{ variables.dns }}"
          keyVaultName: "cvp-${{lower(parameters.env)}}-kvgg"

