trigger:
  - master
pr:
  - master
parameters:
  - name: env
    displayName: Env
    type: string
    default: sbox
    values:
      - sbox
      - stg
      - prod

variables:
  - template: pipeline/variables-common.yaml
  - ${{ if eq(parameters.env, 'sbox') }}:
    # Sandbox (sbox)
    - template: pipeline/variables-sbox.yaml
    - group: cvp-sbox
  - ${{ if eq(parameters.env, 'stg') }}:
    # Staging (stg)
    - template: pipeline/variables-stg.yaml
    - group: cvp-stg
  - ${{ if and(contains(variables['Build.SourceBranch'], 'master'), eq(parameters.env, 'prod')) }}:
    # Production (prod)
    - template: pipeline/variables-prod.yaml
    - group: cvp-prod

stages:
  - stage: Build
    jobs:
      - job: BasicValidation
        steps:
          - template: pipeline/steps/tf-install.yaml
          - task: TerraformCLI@0
            inputs:
              command: 'init'
              commandOptions: '-backend=false'
          - task: TerraformCLI@0
            displayName: Validate Terraform
            inputs:
              command: 'validate'
              commandOptions: '-no-color'
          - script: terraform fmt -check=true
            displayName: Check Formatting

  - stage: Deploy
    dependsOn: Build
    jobs:
      - job: DeployToEnv
        steps:

          - template: pipeline/steps/tf-init.yaml
            parameters:
              subscriptionName: $(subscriptionName)
              product: $(product)
              locationEng: $(locationEng)
              location: $(location)
              env: $(env)

          - template: pipeline/steps/tf-plan.yaml
            parameters:
              subscriptionName: $(subscriptionName)
              env: $(env)
              certName: $(certName)
              location: $(location)
              product: $(product)

  - stage: Wait
    dependsOn: Deploy
    jobs:
      - job: waitForValidation        
        displayName: 'Wait for external validation'
        pool: server
        timeoutInMinutes: 4320 # job times out in 3 days
        steps:
        - task: ManualValidation@0
          timeoutInMinutes: 1440 # task times out in 1 day
          inputs:
            instructions: 'Please validate the Terraform Plan for PROD environment to resume'
            onTimeout: 'reject'

  - stage: Apply
    dependsOn: 
    - Build
    - Wait
    jobs:
     
      - job: ApplytoEnv
        steps:
          - template: pipeline/steps/tf-apply.yaml
            parameters:
              subscriptionName: $(subscriptionName)
              env: $(env)

          - template: pipeline/steps/tf-dynatrace.yaml
            parameters:
              subscriptionName: $(subscriptionName)
              env: $(env)
              location: $(location)
              product: $(product)
