trigger:
  - master
pr:
  - master

resources:
  repositories:
    - repository: azTemplates
      type: github
      name: hmcts/azure-devops-templates
      ref: refs/heads/master
      endpoint: hmcts

parameters:
  - name: envs
    displayName: Environments
    type: object
    values: []
    default: ['sbox','stg','prod'] 
  - name: releaseBranchName 
    displayName: Release branch substring. # if branch is release then will only run in prod. else, will run in all envs but prod env will only run plan
    type: string
    default: 'refs/heads/release'

stages:
  - template: pipeline/stages/build.yaml 

  - ${{each env in parameters.envs}}:
    - template: pipeline/stages/plan.yaml
      parameters:
        env: ${{env}}
        ${{ if and(ne(env, 'prod') , contains(variables['Build.SourceBranch'], parameters.releaseBranchName)) }}:
          runStage: 'false'
        ${{ if and(eq(env, 'stg'), eq(contains(variables['Build.SourceBranch'], parameters.releaseBranchName), False )) }}: # stg env + not release
          runStage: 'true'
          dependsOnEnv: 'sbox'

    - template: pipeline/stages/deploy.yaml
      parameters:
        env: ${{env}}
        ${{ if and(eq(env, 'prod'), contains(variables['Build.SourceBranch'], parameters.releaseBranchName)) }}:  # prod + not release
          runStage: 'true' 
        ${{ if and(ne(env, 'prod'), eq(contains(variables['Build.SourceBranch'], parameters.releaseBranchName), False )) }}: # not prod + not release
          runStage: 'true'

    - template: pipeline/stages/test.yaml
      parameters:
        env: ${{env}}
        ${{ if and(eq(env, 'prod'), contains(variables['Build.SourceBranch'], parameters.releaseBranchName)) }}:  # prod + release
          runStage: 'true' 
        ${{ if and(ne(env, 'prod'), eq(contains(variables['Build.SourceBranch'], parameters.releaseBranchName), False )) }}: # not prod + not release
          runStage: 'true'