trigger:
  - master
pr:
  - master
  
resources:
  repositories:
    - repository: azTemplates
      type: github
      name: hmcts/azure-devops-templates
      ref: refs/heads/master
      endpoint: hmcts

parameters:
  - name: envs
    displayName: Environments
    type: object
    values: []
    default: ['sbox','stg','prod']

stages:
  - template: pipeline/stages/build.yaml 

  - ${{each env in parameters.envs}}:
    - template: pipeline/stages/plan.yaml
      parameters:
        env: ${{env}}
        testRepoBranch: ${{variables['Build.SourceBranch']}}
        ${{ if and(eq(env, 'stg'), eq(contains(variables['Build.SourceBranch'], 'refs/heads/VIH-8722'), False)) }}:
          dependsOnEnv: 'sbox'

    - template: pipeline/stages/deploy.yaml
      parameters:
        env: ${{env}}

    - template: pipeline/stages/test.yaml
      parameters:
        env: ${{env}}