trigger:
  - master
pr:
  - master
  
resources:
  repositories:
    - repository: azTemplates
      type: github
      name: hmcts/azure-devops-templates
      ref: refs/heads/master
      endpoint: hmcts

parameters:
  - name: envs
    displayName: Environments
    type: object
    values: []
    default: ['sbox','stg','prod']

stages:
  - template: pipeline/stages/build.yaml 

  - ${{each env in parameters.envs}}:
    - template: pipeline/stages/plan.yaml
      parameters:
        env: ${{env}}
        testRepoBranch: ${{variables['Build.SourceBranch']}}
        # ${{ if or(eq(env, 'sbox'), contains('refs/heads/hotfix-', 'refs/heads/hotfix-')) }}:
        #   dependsOnEnv: ''
        # ${{ if and(eq(env, 'stg'), eq(contains('refs/heads/hotfix-', 'refs/heads/hotfix-'), False)) }}:
        #   dependsOnEnv: 'sbox'
        # ${{ if and(eq(env, 'prod'), eq(contains('refs/heads/hotfix-', 'refs/heads/hotfix-'), False)) }}:
        #   dependsOnEnv: 'stg'

        ${{ if and(containsValue(['sbox','stg'], env), ne(contains(variables['Build.SourceBranch'], 'refs/heads/release-'), False)) }}:
          runStage: true
        ${{ if and(containsValue(['prod'], env), eq(contains(variables['Build.SourceBranch'], 'refs/heads/release-'), False)) }}:
          runStage: false
        ${{ if and(containsValue(['sbox','stg'], env), eq(contains(variables['Build.SourceBranch'], 'refs/heads/release-'), False)) }}:
          runStage: false
        ${{ if and(containsValue(['prod'], env), eq(contains(variables['Build.SourceBranch'], 'refs/heads/release-'), False)) }}:
          runStage: true
          
    - template: pipeline/stages/deploy.yaml
      parameters:
        env: ${{env}}

    - template: pipeline/stages/test.yaml
      parameters:
        env: ${{env}}


# Every time we do a release, the plan has already been run, so most every time we need to rerun the plan.
# As we cannot do that without creating a new release, we always create a 'hotfix' branch so we can by pass the other environments.

# Instead we would like every thing that is not with the 'release/' branch path to deploy to sbox and stg, then run the production plan but that is all.
# If the branch is within the 'release/' branch path then it should run the Build, Plan, Wait, Deploy and Test stages.